builds:
  skip: true
archives:
  meta: true
checksum:
  disable: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  prerelease: auto
  mode: append
  skip_upload: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
