version: 3
vars:
  IDF_VERSION: v5.0
tasks:
  default:
    cmds:
      - task -l
    interactive: true
  download:
    cmds:
      - mkdir -p archives
      - curl -L https://github.com/espressif/esp-idf/releases/download/{{.IDF_VERSION}}/esp-idf-{{.IDF_VERSION}}.zip -o archives/esp-idf-{{.IDF_VERSION}}.zip
    status:
      - test -f archives/esp-idf-{{.IDF_VERSION}}.zip
  setup:
    desc: Setup the SDK
    deps:
      - download
    cmds:
      - unzip -u archives/esp-idf-{{.IDF_VERSION}}.zip
      - ./esp-idf-{{.IDF_VERSION}}/install.sh
  build:
    desc: Build the firmware image
    cmds:
      - idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults" build
      - |
        esptool.py \
        --chip esp32c3 \
        merge_bin \
        --target-offset 0x0 \
        --fill-flash-size 2MB \
        --output build/progress-bar-flash.bin \
        0x0 build/bootloader/bootloader.bin \
        0x8000 build/partition_table/partition-table.bin \
        0x10000 build/progress-bar.bin
    env:
      IDF_PATH: '{{.PWD}}/esp-idf-{{.IDF_VERSION}}'
  flash:
    desc: Flash firmware image to the device
    cmds:
      - |
        esptool.py \
        --port {{.CLI_ARGS}} \
        --before default_reset \
        --after no_reset \
        --chip esp32c3 \
        write_flash \
        0x0 build/progress-bar-flash.bin
    preconditions:
      - sh: test -f build/progress-bar-flash.bin
        msg: No flashable binary found.
  erase:
    desc: Erase the flash chip of the device
    cmds:
      - |
        esptool.py \
        --port {{.CLI_ARGS}} \
        --before default_reset \
        --after no_reset \
        --chip esp32c3 \
        erase_flash
