name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build firmware
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project update
            do build
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: progress-bar-firmware-${{ github.sha }}
          path: build/progress-bar-flash.bin
