name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DAGGER_CACHE_BASE: dagger-ci-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env vars on push to main
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-main" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-main" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Set env vars on pull request
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-main type=gha,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
      - name: Build firmware
        uses: dagger/dagger-for-github@v3.1.0
        with:
          version: v0.2.36
          cmds: |
            project update
            do build
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: progress-bar-firmware-${{ github.sha }}
          path: build/progress-bar-flash.bin
