name: Lint
on:
  pull_request:
    branches:
      - main
jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit-Lint
        uses: wagoid/commitlint-github-action@v5
